import type { AppData, BackupHealth } from "../types";
import { SCHEMA_VERSION } from "../types";
import {
  createBackup,
  encryptBackup,
  parseBackup,
  validateData,
} from "./backup";

export function backupHealthLabel(health?: BackupHealth) {
  return !health
    ? "未確認"
    : health.status === "normal"
      ? "正常"
      : health.status === "failed"
        ? "失敗"
        : "要確認";
}
/** A browser can verify its generated bytes, but cannot verify a saved OS file. */
export async function checkedEncryptedBackup(data: AppData, password: string) {
  const original = validateData(data);
  const text = await encryptBackup(original, password);
  const restored = await parseBackup(text, password);
  const a = JSON.parse(createBackup(original)),
    b = JSON.parse(createBackup(restored));
  if (JSON.stringify(a.data) !== JSON.stringify(b.data))
    throw new Error("復元の確認が一致しません。元の記録は変更していません。");
  const health: BackupHealth = {
    status: "review",
    checkedAt: new Date().toISOString(),
    encrypted: true,
    schemaVersion: SCHEMA_VERSION,
    bytes: new Blob([text]).size,
    savedConfirmed: false,
  };
  if (!health.bytes) throw new Error("バックアップが空です。");
  return { text, health };
}
